### ISSUE TITLE
Fresh install with python 3.6 requires yarl rollback

### ISSUE THREAD

**Issue by wawiesel** [jgayfer/pydest#10]
Verifying install I get:
```
$ python3
Python 3.6.6 (default, Jun 28 2018, 05:43:53)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import  pydest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ww5/dev/pydest/pydest/__init__.py", line 4, in <module>
    from .api import API
  File "/Users/ww5/dev/pydest/pydest/api.py", line 1, in <module>
    import aiohttp
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client.py", line 15, in <module>
    from . import connector as connector_mod
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 17, in <module>
    from .client_proto import ResponseHandler
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client_proto.py", line 6, in <module>
    from .http import HttpResponseParser, StreamWriter
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/http.py", line 8, in <module>
    from .http_parser import (HttpParser, HttpRequestParser, HttpResponseParser,
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/http_parser.py", line 15, in <module>
    from .http_writer import HttpVersion, HttpVersion10
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/http_writer.py", line 304, in <module>
    class URL(yarl.URL):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yarl/__init__.py", line 231, in __init_subclass__
    raise TypeError("Inheritance a class {!r} from URL " "is forbidden".format(cls))
TypeError: Inheritance a class <class 'aiohttp.http_writer.URL'> from URL is forbidden
```
Once I do this:
```
sudo -H pip-3.6 install "yarl<1.2"
```
all is well. Apparently "yarl 1.3.0" was too much.

**Comment by jgayfer** [comment]
This has been fixed with an upgrade of `aiohttp` 👍
