### ISSUE TITLE
Manifest Permission denied

### ISSUE THREAD

**Issue by dearvoodoo** [jgayfer/pydest#26]
Hello I'm getting an error while trying to get information from manifest.
`[Errno 13] Permission denied: 'manifest_zip'`

Full Error:
```
Exception in command 'xur'
Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/redbot/cogs/where_is_xur/where_is_xur.py", line 180, in xur
    item = await destiny.decode_hash(i, 'DestinyInventoryItemDefinition')
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/pydest/pydest.py", line 38, in decode_hash
    return await self._manifest.decode_hash(hash_id, definition, language)
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/pydest/manifest.py", line 40, in decode_hash
    await self.update_manifest(language)
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/pydest/manifest.py", line 89, in update_manifest
    filename = await self._download_file(manifest_url, MANIFEST_ZIP)
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/pydest/manifest.py", line 113, in _download_file
    with open(filename, 'wb') as f_handle:
PermissionError: [Errno 13] Permission denied: 'manifest_zip'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/ubuntu/redenv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: PermissionError: [Errno 13] Permission denied: 'manifest_zip'
```

**Comment by jgayfer** [comment]
Hello. Crazy late response. Apologies.

Usually I'd ask if you can provide a specific code example, but since this is almost two years old, I'm going to mark it as closed. Please re-open if you'd like to discuss further.
